version: '2.2'
services:
  mongo1:
    restart: always
    environment:
      MONGO_ROLE: primary
    tty: true
    hostname: mongo1
    image: mongo-rep-set:3.4-centos
    networks:
      default:
        aliases:
          - mongo1
    stdin_open: true

  mongo2:
    restart: always
    tty: true
    hostname: mongo2
    image: mongo-rep-set:3.4-centos
    networks:
      default:
        aliases:
          - mongo2
    stdin_open: true

  mongo3:
    restart: always
    environment:
      JOURNALING: 'no'
    tty: true
    hostname: mongo3
    image: mongo-rep-set:3.4-centos
    networks:
      default:
        aliases:
          - mongo3
    stdin_open: true
networks:
  default:
